language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack: teamcarnell:zhTADgjsb7yJ5RPEd7LPNFwI
  email:
  - carnell28@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: eN2axfNoK2mP1YLFxxxithyMZD3KPy1ZFavzDGBrpzBxpvolbvzHMl8gc/CeufWR1ubyQzZFt0aPRLyMJD06MkorwrSTbPZ6TpQYHKwE9/l7TGkfEe8QC5dTbonacSrSx6d33XNVS/ZzWMnrltDlq0eOpl63GtIJmuc7WLnDynFWTCLIcoNpieAFgWNj+8PTpayy6pEX3xBQUgqOfiQOCIPjrycmh4a7DkQEjTnRpmwU1fiIgyH+sFINtr62aSHP0Rs0TEYj4AhowJ4iRY6W/Pnx//vFzA1+lLapzKxKBV9sMDg0TaqY0DBniKaT7tSKcvXdmK0YcAMX9fJXPv7pVMk3zO88b1dOu9kD2IWVSG4D/7LDJZhDdcyoUcD9JzoWsSwDLG77qM6f29VnIVxhf5Jql058GJOf4vxmenKknaWPd+Eg6EttSUOS3BwBxxXCTO4L5zhQ+OOo51fCfS1GjxiRQPETQKxHcvRUBpZF9h47V0anWt4wfAzam1UTVcKuAEmCqfRtSWawFwLFCet/gF5XTFu8yg5eKlg7YL8WzdW8qvlay3hEGPoct+MAfX+yfbKefBEsHx1cFQv19AG4Sg7M5jSyr0H3C41l+gPNrqzgU0wsFmMec9ymqcWpoPP760NKol/TtiUtZLUozXKegzbk5sDUs1fBDVO7ZyjuMS0=
  - secure: a5bUcBvabSwJZtoUZBqYTkJj7ggi80BDzanni/KV6cTNaAaAyVAA+qZsdnD07FfZzZybrb24ngaeFODzVw9SW0ogdX2JtDYqQkYIfx8LlF3Ms3Gu84yKMvHRQhgJCbDuZiZddy6cb16KaJ1mBsnymcXTOjV1dKXNlP5FF8VdV7t3x4q3z2pb7v3F7H9hCsR1tk8yrq5EV9flDQjbZtaIWEb8Z5EiRlD+03+mhCitIhZ5lMRs8yOjVQfjdLLchLoImV8UVoXYww9/RjHO+FU/cChAre418zC/BKbQJcF8tXD2EL8R+XZ3RKSy4NQMuMyiYtIN1GQIfJB34yEaF0cG/UrHtMvmbVUfsQ35zsej45UG1a+KLY79IET5nbrFMgUrhF81cOwFXDSYkzN9ffUXHb2UqAS7UL/W8oi2h7tPpUwlLhmODh1QECB6P2mv7WHTcYKApAV0nmmzc7wjKv8GWXrpNvUv6J0QFaZNreX18EULErkX6EtkM1THrxGKyBwlpx0XPkAwHkFgkgoIG8PO4wHcoGXlFxAWCxtWhIeo+FD2WWuR9wfjcVksd6NgYBHt67LOXmDL9wckR3jFDMJog2ADIwDM40kMqXwiFTuw/kCnZ0JyrUMqCJhBcxPxya8wRMcPDe2i+or30s/QEsp3Xgbf3Tr47zzM7T+cDoF/y/k=
  matrix:
  - TEST_DIR=chapter1-code;TMX_DOCKER_IMAGE=johncarnell/tmx-simple-service:chapter1
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $TMX_DOCKER_IMAGE
